### ISSUE TITLE
There is CORS issue

### ISSUE THREAD

**Issue by AlexHsieh** [teamhanko/hanko-vue-express-starter#1]
`Access to XMLHttpRequest at 'https://6f39ece9-74d9-4b7e-aa14-0cda164cdd49.hanko.io/.well-known/config' from origin 'http://localhost:5173' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Any suggestion how I can handle this?

**Comment by Ashutosh-Bhadauriya** [comment]
Hey @AlexHsieh this error occurs most probably when you have not configured the project correctly on Hanko cloud. When creating a project, you need to pass `http://localhost:5173` as a project url. Can you make sure you have done that?

You can follow this guide to get a better idea: https://docs.hanko.io/setup-hanko-cloud

**Comment by AlexHsieh** [comment]
It works. thanks for the prompt response. 🙂
